feeder: dataset.dataloader_video.BaseFeeder 

phase: train
dataset: phoenix2014
num_epoch: 40
work_dir: ./work_dir/swin_mstp/ 
batch_size: 2
random_seed: 0
test_batch_size: 1
num_worker: 8
device: 0
log_interval: 50
eval_interval: 1
save_interval: 5
evaluate_tool: sclite
loss_weights:
  SeqCTC: 1.0
  # VAC
  ConvCTC: 1.0
  Dist: 10.0 
#load_weights: ""
optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [20,30]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network_Swin_MSTP.SLRModel 
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: swin_s #swin_t mac_r18
  conv_type: 2
  use_bn: 1
  share_classifier: True
  weight_norm: True 
